### ISSUE TITLE
conda-forge license violation

### ISSUE THREAD

**Issue by isuruf** [prefix-dev/reproducible-builds#182]
The recipes here are modified recipe scripts from conda-forge and therefore are subjected to conda-forge's BSD-3-Clause license. Please distribute that license notice and copyright here in the repo and in all the artifacts that you produce. (For eg: in each conda package in conda-forge, we distribute the license as `info/recipe/parent/recipe-scripts-license`.

**Comment by wolfv** [comment]
Would you be OK with a single license file e.g. in the root of the repository?

I am currently thinking about ways we could embed it easily into all the artifacts, but it might be a little tricky (we would ideally copy it into the recipe folder prior to each build).

**Comment by isuruf** [comment]
> Would you be OK with a single license file e.g. in the root of the repository?

I think that's okay.

**Comment by Hofer-Julian** [comment]
> > Would you be OK with a single license file e.g. in the root of the repository?
> 
> I think that's okay.

I just checked out the repo, and there is already a [LICENSE file](https://github.com/prefix-dev/reproducible-builds/blob/main/LICENSE) containing a BSD-3 Clause license. Can this issue be closed then @isuruf?

**Comment by wolfv** [comment]
@Hofer-Julian that license file only mentions prefix whcih is not correct.

**Comment by Hofer-Julian** [comment]
Fair point, I've opened a PR for clarifying that we adapted the recipes from conda-forge as a first step: https://github.com/prefix-dev/reproducible-builds/pull/184

**Comment by mbargull** [comment]
FYi, we discussed this at today's conda-forge/core meeting -- not just wrt. this repo, but general downstream/other uses of conda-forge's recipes.
Specifically, we mostly discussed how to handle/better document the
> \[...\] and in all the artifacts that you produce. (For eg: in each conda package in conda-forge, we distribute the license as `info/recipe/parent/recipe-scripts-license`.

part since this is currently done via scripts from the `.scripts/` directory in conda-forge's feedstocks and thus missed if recipes are built without running those downstream.
