### ISSUE TITLE
Find out why recipes are not reproducible and if we can fix them

### ISSUE THREAD

**Issue by tdejager** [prefix-dev/reproducible-builds#40]
From preliminary results, some recipes already not seem reproducible e.g `pthreads-stubs`

Either we need to:

* Fix them, with a patch or w/e so they are reproducible or,
* Mark them as not reproducible and show that on the README somehow.

**Comment by nichmor** [comment]
Closing because we create separate issue per recipe to track them better:
https://github.com/prefix-dev/reproducible-builds/issues/75
